### ISSUE TITLE
Add validation for checkboxes/radio input types

### ISSUE THREAD

**Issue by muudles** [turinggroup/angular-validator#1]
Hi, just wondering if you're planning to update with support for checkbox and radio input types?

**Comment by chamarts** [comment]
Hi Jakobovski,

is this in place already ? right now I see messages are coming next to the radio input instead of the label next to the radio/checkbox, is there a way we can supply our own message label instead of creating a new sibling ? 

thx
srinivas

**Comment by Jakobovski** [comment]
See #17. Hopefully this will be implemented this weekend

**Comment by chamarts** [comment]
hi, how do I add validations for select boxes/ checkboxes ?
