### ISSUE TITLE
How to use nested form and its validation

### ISSUE THREAD

**Issue by achalj09** [turinggroup/angular-validator#109]
I have to validate nested forms.

Sub form have its own validation, but when i declared nested forms it's validating the unput field but submitting the main form also.
![screenshot-localhost 9000 2017-01-12 18-44-44](https://cloud.githubusercontent.com/assets/8180139/21891204/781cddde-d8f7-11e6-8020-61b60761a778.png)

**Comment by Jakobovski** [comment]
Nested forms are a bad practice and not be done: See http://stackoverflow.com/questions/379610/can-you-nest-html-forms
