### ISSUE TITLE
Do not automatically generate <label>. only use ngMessages.

### ISSUE THREAD

**Issue by JSlain** [turinggroup/angular-validator#111]
I see in the **Feature** list:

> Supports custom validation message templates and placement using Angular's native ngMessages directive.

We want complete control over the way we display the error messages, so i thought about using this feature. The messages actually appears as we wishes in our \<div ng-messages ... \> , but angular-validator still adds it's own generated \<label\> at some location we definitely don't want.

Is there a way to disable the auto-generated \<label\>?

**Comment by mrmashal** [comment]
Would you mind including a sample using ngMessages in the docs?

**Comment by Jakobovski** [comment]
merged thanks!

**Comment by JSlain** [comment]
@mrmashal I tried but i had conflict with versions of angular. Since i don't know bower very much, it was simpler for me to just remove it and make an example using native angular directives.

I'll take some time to figure out how it works and put back my angular-messages example, in another pull request. Angular-messages is not exactly related to my modification, but an example using it could be very useful. Indeed.
