### ISSUE TITLE
Reset Form from Controller

### ISSUE THREAD

**Issue by otterslide** [turinggroup/angular-validator#122]
If I clear out the model from the controller the form ends up showing errors for all the fields.

How can I reset the form from the controller after the form is submitted, for example a password change form ? Is there some way to pass the handle to the form and call .reset() on it?
`angular-validator-submit="ctrl.changePassword(form.password)"`

thanks.

**Comment by otterslide** [comment]
I just used the form's name angular-validator-submit="ctrl.changePassword(form.password, formName)" and it worked.

**Comment by kirajhpang** [comment]
@otterslide Hi, interesting answer, but do you get this work on latest version?
this is mine update based on your answer.
```
angular-validator-submit="pageController.submitCountryOnClicked(countryForm.name, countryForm);" name="countryForm"
```

**Comment by kirajhpang** [comment]
@otterslide sorry, I was able to get the reset by using this method. Thanks anyway
