### ISSUE TITLE
Include a "name" and "version" tag in package.json

### ISSUE THREAD

**Issue by lydongray** [turinggroup/angular-validator#129]
Could you please include a "name" and "version" tag in package.json?
Thanks.

https://docs.npmjs.com/getting-started/using-a-package.json

As a bare minimum, a package.json must have:

"name"
all lowercase
one word, no spaces
dashes and underscores allowed
"version"
in the form of x.x.x
follows semver spec
For example:

{
  "name": "my-awesome-package",
  "version": "1.0.0"
}

**Comment by Jakobovski** [comment]
Feel free to contribute
