### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by zeetarian** [turinggroup/angular-validator#132]
I guess valid email address is zeetarian@gmail.com, where as when I put only zeetarian@gmail, this librarys give me OK message.

Is it a bug or I am not testing it proper.

![image](https://user-images.githubusercontent.com/25389057/30518254-d3e17c80-9b91-11e7-908e-ce4af088288b.png)

Regards,

**Comment by Jakobovski** [comment]
Technically that's a valid email address. 

If you want a more strict email validation you can use regex
