### ISSUE TITLE
Form elements inside ng-if are getting ignored

### ISSUE THREAD

**Issue by jblaketc** [turinggroup/angular-validator#14]
Hey, I have some inputs that are usually hidden on page load, and then when a value in the model changes, they get shown. One looks like such:

```javascript
<span class="input-group" ng-if="specs.valueType == 'static'">
                                        <input class="form-control" ng-model="specs.value" 
                                               validation-label="specValueLabel" 
                                               name="specValue" 
                                               required 
                                               />
                                        <label name="specValueLabel"></label>
                                    </span>
```
From what I can tell, because the watchers get attached on form render, I'm wonder if you know how to account for inputs getting added later on. If I use a ng-show instead, then some inputs that are hidden would get validated when they're not needed within the context of the form. 

Here's a plnkr. http://plnkr.co/edit/N3pbGR61LfFfyYnK8rFB?p=preview

If you select the first option 'some', the box shows up and it gets validated on submit, but the message doesn't show if you leave it blank. When you select 'other', the form submits just fine. I need it to show the message on the input if it's visible and invalid.

 Thanks

**Comment by Jakobovski** [comment]
This has been fixed in the latest release
