### ISSUE TITLE
Changes in ng-required do not update the messages

### ISSUE THREAD

**Issue by ondrap** [turinggroup/angular-validator#15]
When I have an element that has ng-required that changes from false to true AFTER the form validation, the message on this element is not shown when the ng-required is changed.

Solution: add 'element.required' to the $watch function, ie:
```
return elementToWatch.required + elementToWatch.value + scopeForm.submitted + checkElementValididty(elementToWatch) + getDirtyValue(scopeForm[elementToWatch.name]);
 ```

**Comment by Jakobovski** [comment]
Hi ondrap,

Sorry for the late response. Would you be able to make the changes and then create a pull request?

**Comment by Jakobovski** [comment]
Fixed in latest release
