### ISSUE TITLE
Dynamically created fields do not modify the form's $invalid state.

### ISSUE THREAD

**Issue by RaXaR** [turinggroup/angular-validator#20]
Hi, great plugin. 

The issue i am having is that I am not sure how to get angular-validator to $watch fields that have been added with $compile and .append() to the form. 

So currently, after an .append(), the wrapping form's validation isn't changed even if the field is invalid.

Any suggestions/ideas would be greatly appreciated.

Thanks.

**Comment by Jakobovski** [comment]
Can you please create a plunkr to demonstrate the issue?

**Comment by chamarts** [comment]
http://plnkr.co/edit/Yf6sT0xiLinlhGoinLSY?p=preview

**Comment by chamarts** [comment]
HI, I have similar issue, I am dynamically generating the checkboxes and while validating the form, I am not seeing the error messages displayed for the checkboxes. 
please look at the plunker for the issue http://plnkr.co/edit/Yf6sT0xiLinlhGoinLSY?p=preview

**Comment by chamarts** [comment]
any comments on my plunker code ?

**Comment by RaXaR** [comment]
@Jakobovski, @chamarts  As far as I could tell, in my use case the fields do not get added to the validator's .watch(). So basically the validator is unaware of them. I thought about writing a small method to add the fields manually but time constraints didn't allow it. I ended up using plain old HTML for the fields as a workaround. I hope this helps.

**Comment by Jakobovski** [comment]
@chamarts... RaXar is correct. The validator is not setup to watch dynamically created fields. This is a feature that I have been meaning to add to the validator, but I have not had a chance to do it yet. 

If you are interested in implementing it let me know!

**Comment by Jakobovski** [comment]
This has been fixed in the latest version

**Comment by chamarts** [comment]
This is working great !. but looks like its missing changes committed by https://github.com/turinggroup/angular-validator/issues/17 @wulftone.
