### ISSUE TITLE
focus on first invalid element

### ISSUE THREAD

**Issue by chamarts** [turinggroup/angular-validator#22]
Hi,

not sure if its already in place, but just wanted to check if theres a way to focus on the first invalid element on errors ?

thx
sri

**Comment by melvinmmw** [comment]
need that as well :)))

**Comment by arajay** [comment]
it looks like the default functionality attempts to scroll the user to the closest .validationMessage; it does not actually add focus to the actual input. 

Additionally if you are hiding those labels or using absolute positioning on them to fake tooltip styles, then it doesn't jump to the label.

Please update to add focus to the closest or first input with .has-error.
