### ISSUE TITLE
Form in the demo does not get reset

### ISSUE THREAD

**Issue by ahmad19** [turinggroup/angular-validator#23]
Hello, 

I just found out that your form does not get reset after submission. So i try to add `$scope.myForm = {};`
But it dint work.

**Comment by karna41317** [comment]
Yup , I have same issue

**Comment by vkeziah** [comment]
I too have the same problem , can you please tell me how to do this ..

**Comment by Jakobovski** [comment]
This functionality has now been added v1.2.5.  Please see the readme and plunkr for details.
