### ISSUE TITLE
Email Validation not working

### ISSUE THREAD

**Issue by decipher08** [turinggroup/angular-validator#24]
Hi,
If I enter a@gmail instead of a@gmail.com its not showing error.

![image](https://cloud.githubusercontent.com/assets/10865208/6246090/21235ccc-b78b-11e4-92d1-47e23f3ad9bc.png)

How to fix it.

Thanks

**Comment by Jakobovski** [comment]
Hi,

This is actually not an error. a@gmail IS a valid email address and that is why it is not showing an error. If you would like to make sure that user enters a `.com .org, .net` etc.. at the end of the address you can easily create a custom validator. See the readme for more info
