### ISSUE TITLE
it doesn´t work with ui-select

### ISSUE THREAD

**Issue by reds071286** [turinggroup/angular-validator#27]
Hello, sorry for my English, please help me, i need to use this project with  select control, i´m using ui-select project and i need to validate if the user has choosen one option, if not, i need to show a required message. So, am I doing something wrong? or this project doesn´t support ui-select control?, here is my plunk http://plnkr.co/edit/6IApfRtmXqrzOlpQH5cM?p=preview

**Comment by Jakobovski** [comment]
Hi,
The project does not currently support UI-select. If you would like to contribute support for UI-select directives that would be awesome.
