### ISSUE TITLE
Doesn't work in FF

### ISSUE THREAD

**Issue by pankajparkar** [turinggroup/angular-validator#28]
I tried the demo plunkr given on Github page, It is not giving validation on Firefox.

http://plnkr.co/edit/ceBvMhU5se2mJYWHk3Ne?p=preview

**Comment by Jakobovski** [comment]
It works for me. What version of firefox are you using? What OS? 

Are you getting any errors in the console? If so what are they. Please include screenshots and whatever relevant information you can.

**Comment by pankajparkar** [comment]
My FF version is 19.0.2 (Refer screen shot FFConsoleErrors)

I'm using Windows 8.1
Yes I'm getting error in my console (Refer screen shot  firefoxversion.png)
Also scroll bar is not working, two getting bottom of the page I need to use `tab` key 

![firefoxversion](https://cloud.githubusercontent.com/assets/5320044/6547027/adc8e3d6-c5f0-11e4-8e98-cc794ebc85ab.png)
![ffconsoleerrors](https://cloud.githubusercontent.com/assets/5320044/6547028/adfabf64-c5f0-11e4-95d3-5b8e9d4653fc.png)

**Comment by Jakobovski** [comment]
It looks like an issue with one of your plugins, or plunker... Do you have the issue in chrome?

**Comment by pankajparkar** [comment]
No I don't having issue in chrome browser, but when I tried with different machine(Windows 7), it works. What would be the cause of it? Did you tried on Windows 8?

**Comment by Jakobovski** [comment]
I didn’t try in windows 8. Do other plunkers work for you on windows 8? From looking at the errors it looks like an error with plunker and not the validator.


Zohar Jackson
Lead Frontend Developer
O:  312-488-4690
C:  224-612-1338

**Comment by pankajparkar** [comment]
I believe there was an issue with my Internet, It works like a charm now. Thanks for your support

**Comment by Jakobovski** [comment]
Ha ha... glad to hear.
