### ISSUE TITLE
Provide a way to configure the CSS error class

### ISSUE THREAD

**Issue by thiagodp** [turinggroup/angular-validator#30]
Instead of just using `has-error`, it would be nice if we could to configure the error class.

**Comment by Jakobovski** [comment]
Well... You can use CSS to define `.has-error` to be whatever you want. If your using less or sass you can make `.has-error` inherit from other classes.

**Comment by thiagodp** [comment]
But what if you already use another class everywhere and would like to use that class instead of ```has-error```? A team used to use another class in a project won't start using ```has-error``` and have to maintain both... (less/sass make it easier, but it's not the case)

**Comment by Jakobovski** [comment]
If you want you can make a pull request for this, but i am not going to implement it. Its pretty trivial to make the `.has-error` class inherit from your current class using sass or less.
