### ISSUE TITLE
why my validator function is called repeatedly (4/6 times) ?

### ISSUE THREAD

**Issue by chamarts** [turinggroup/angular-validator#34]
I have added a validator function and I was debugging the function for some reason and noticed that the validator function is called min of four to six times. any reason why is it called repeatedly ? 

and also in IE, the function fail to consider the return value from the validator function. it always show invalid message irrespective of true/false return value.

**Comment by Jakobovski** [comment]
This has to do with how the angular digest cycle works. This is not an issue.

Please create plunker of IE issue

**Comment by Jakobovski** [comment]
I am closing this issue. As you have not responded.
