### ISSUE TITLE
integrating with angular-formly 

### ISSUE THREAD

**Issue by chamarts** [turinggroup/angular-validator#35]
Hi,

how does it integrate with angular-formly ? the form is generated dynamically using json fields. so just wanted to check if anyone has done any integrated validator with formly ?

thx
sri

**Comment by Jakobovski** [comment]
Hi,

I am not familiar with anuglar-formly. If formly has the ability to add the angular-validator tags to the form elements then it should work. You may need to change the priorities of the two directives so that angular-validator compiles after formly

**Comment by chamarts** [comment]
ok, since the  formly adds the input  fields dynamically from json data, I thought thats an issue with angular validator since it expects field names input fields. will try it out myself and update the thread.

thx for quick update. 


thx
srinivas
