### ISSUE TITLE
Missing "var" declaration

### ISSUE THREAD

**Issue by dlear** [turinggroup/angular-validator#39]
This is a minor issue, but I think you have a `var` declaration missing on `isDirtyElement`:

    // Determine if the element in question is to be updated on blur
    isDirtyElement = "validate-on" in ...

**Comment by Jakobovski** [comment]
Thanks. Would you like to make a pull request.

**Comment by dlear** [comment]
Created PR https://github.com/turinggroup/angular-validator/pull/43

**Comment by Jakobovski** [comment]
Awesome.. Can you run 'grunt build' in the directory to update the minified distribution file. Then i will pull the request. Thanks for your help.

**Comment by Jakobovski** [comment]
see the CONTRIBUTING.md in the root directory.

**Comment by dlear** [comment]
I’m new to github – I think I’ve updated the pull request with the built and tested dist.

Let me know if I’ve done it wrong.

Dave
