### ISSUE TITLE
`validate-on` property

### ISSUE THREAD

**Issue by pljspahn** [turinggroup/angular-validator#41]
I cannot find any documentation describing what we can do with `validate-on`. The demo you provide only uses `dirty`.

Can this be used to trigger validation on a form when other model's value changes?

I need to trigger validation on a field when another (arbitrary) model's value changes.

**Comment by Jakobovski** [comment]
Yes this is possible. Validate on 'dirty'. See the password example in the demo

**Comment by poppahorse** [comment]
> I need to trigger validation on a field when another (arbitrary) model's value changes.

@Jakobovski the password demo seems to validate `this` field based on another fields value.

I think what @pljspahn meant (and would be helpful to me is..) is it possible to trigger validation on another field based on 'this' field changing?

Similar to https://github.com/turinggroup/angular-validator/issues/31

**Comment by poppahorse** [comment]
Actually this works nicely - http://plnkr.co/edit/F49pI6nH2gyN5f9LGvp1?p=preview

**Comment by poppahorse** [comment]
I have been having a play here:
http://plnkr.co/edit/F49pI6nH2gyN5f9LGvp1?p=preview

It works on submit, but dont think its possible to chain watch other fields if using dirty. Any ideas?
