### ISSUE TITLE
has-error class in select

### ISSUE THREAD

**Issue by nestorvanz** [turinggroup/angular-validator#42]
I'm validating an select input, the invalid message is showing well, but the color of the label and the border of select is not red. This is because the validator is not adding the 'has-error' class to parent div.

**Comment by nestorvanz** [comment]
Solved. Just add this conde after line 142:
if( !isElementValid ) scopeForm[element.name].$invalid = !isElementValid;

**Comment by Jakobovski** [comment]
Would you like to create a pull request?

**Comment by nestorvanz** [comment]
yes, i like, but i don't have the minified file

**Comment by nestorvanz** [comment]
Hey, i send you a pull request for this isue.

**Comment by Jakobovski** [comment]
See http://plnkr.co/edit/EygwhqIOGYFSBSXXEr54?p=preview
