### ISSUE TITLE
regex validation not work properly

### ISSUE THREAD

**Issue by navid-dada** [turinggroup/angular-validator#46]
i create an input element with this regex validation rule by this code :

<input name="txtMobile" 
                               id="txtMobile" 
                               type="number" 
                               class="form-control input-sm" 
                               maxlength="11" 
                               ng-model="user.mobileno" 
                               required=""
                                ng-pattern="/^09[0-9]{9}$/"
                               validate-on='blur'
                               required-message = "'شماره تلفن همراه را وارد کنید.'"
                               invalid-message = "'شماره تلفن همراه معتبر نیست.'"/>
and this input must accept (09XXXXXXXXXX) witch every X is a digit but this accept nothing

**Comment by Jakobovski** [comment]
Please create a plunker demonstrating the issue.

**Comment by Jakobovski** [comment]
It works fine for me. Set the encoding on your page to `utf-8', maybe thats the issue.

**Comment by Jakobovski** [comment]
See: http://plnkr.co/edit/QXzFhJVvP8FVse7SIzRX?p=preview
