### ISSUE TITLE
How to use angular validator with ng-repeater

### ISSUE THREAD

**Issue by TinoPham** [turinggroup/angular-validator#48]
I use angular validator directive with ng-repeater but It's not work. Here my code:
http://plnkr.co/edit/aeonfK97eKfODjKrV5oC?p=preview

error: Cannot read property '$setValidity' of undefined   at checkElementValidity

please help me!

**Comment by corientdev** [comment]
+1 not working with ng-repeat as it look for a  name tag of input and if it found 2 input with same name then it doesn't work or better to say it work only if both the input boxes fail to match the criteria

**Comment by TinoPham** [comment]
@corientdev : I used name with $index ( input with tag name: name{{$index}} ) but It's not working yet. 

Anybody help me?

**Comment by Jakobovski** [comment]
This should be fixed in latest 1.2.7 build

**Comment by nestorvanz** [comment]
Did you have an example to use with ng-repeat?

**Comment by enkodellc** [comment]
Here is a plunker with the ng-repeat working, http://plnkr.co/edit/qFCan3Rfi5qPEksTniiE?p=preview
