### ISSUE TITLE
Destructors and cleanup

### ISSUE THREAD

**Issue by azamanaza** [turinggroup/angular-validator#51]
When fields are wrapped in "ng-if", when toggling forms when they are "processing" throws undefined errors on line 142

scopeForm[element.name].$setValidity("angularValidator", isElementValid);

You need to add a destructor.

In the meantime, I fixed this using ng-hide/show. ng-if completely removes an element - this is good when you're dealing with lots of forms since you only want have watchers for what is actually visible.

**Comment by Jakobovski** [comment]
This is fixed in latest 1.2.7 build
