### ISSUE TITLE
Bower Bootstrap dependency should be removed

### ISSUE THREAD

**Issue by jonbern** [turinggroup/angular-validator#54]
According to the documentation, angular-validator supports Bootstrap but it's not a requirement. At the same time Bootstrap is listed as a dependency in bower.json. This means Bootstrap and its dependencies (jQuery) will be installed when using angular-validator on a project. 

I really like angular-validator and I think it's a big step up compared to the basic Angular way of doing validation. But since my project is not using Bootstrap and jQuery, I can't justify the extra space impact of using angular-validator when it adds both Bootstrap and jQuery to my project. 

Would it be possible to remove Bootstrap as a dependency in bower.json?

Also, angular-mocks has been listed as a dependency as well. Shouldn't this be listed as a dev-dependency instead?

**Comment by Jakobovski** [comment]
Hi Jon,

You are correct. If you create a PR and update bower.json as you suggested I will merge it.

**Comment by jonbern** [comment]
Hi Jakob,

I have requested a PR for it now. Please have a look.

Cheers

**Comment by keithl8041** [comment]
I can see the PR has been merged but it's still pulling down Bootstrap, jQuery and FontAwesome when installing via bower >>
```
E:\projects\etc>bower install tg-angular-validator
bower cached        git://github.com/turinggroup/angular-validator.git#1.2.7
bower validate      1.2.7 against git://github.com/turinggroup/angular-validator
.git#*
bower cached        git://github.com/twbs/bootstrap.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap.git#>=3.2.0
bower cached        git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower validate      4.4.0 against git://github.com/FortAwesome/Font-Awesome.git#
>=4.0.3
bower cached        git://github.com/angular/bower-angular-mocks.git#1.4.5
bower validate      1.4.5 against git://github.com/angular/bower-angular-mocks.g
it#~1.4.1
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.1
bower install       tg-angular-validator#1.2.7
bower install       font-awesome#4.4.0
bower install       angular-mocks#1.4.5
bower install       bootstrap#3.3.5
bower install       jquery#2.1.4

tg-angular-validator#1.2.7 etc\Scripts\libs\tg-angular-validator
├── angular#1.4.5
├── angular-mocks#1.4.5
├── bootstrap#3.3.5
└── font-awesome#4.4.0

font-awesome#4.4.0 etc\Scripts\libs\font-awesome

angular-mocks#1.4.5 etc\Scripts\libs\angular-mocks
└── angular#1.4.5

bootstrap#3.3.5 etc\Scripts\libs\bootstrap
└── jquery#2.1.4

jquery#2.1.4 etc\Scripts\libs\jquery
```

**Comment by Jakobovski** [comment]
Fixed.
