### ISSUE TITLE
Nested Forms

### ISSUE THREAD

**Issue by storrisi** [turinggroup/angular-validator#56]
I try to use the library to validate fields in a nested form, which i created with ng-form="innerForm", but the library throws this exception, maybe because it can find the element name in the main form:

`TypeError: Cannot read property '$setValidity' of undefined at checkElementValidity (angular-validator.min.js:151)`

**Comment by zortnac** [comment]
I think nested ngForms live in scope according to how they're nested:

```html
<form name="foo">
  <ng-form name="bar">
    <input name="baz">
```    

...exists on scope as `$scope.foo.bar.baz`, but there's a loop that's leaving out the middle part (the ng-form name), trying to find it at `$scope.foo.baz`.

Not sure what the solution might be but I noticed this as well. I bet looking at the source ng-form and seeing how the nesting is handled there might be a good lead.

**Comment by Jakobovski** [comment]
Will not fix.

**Comment by jblaketc** [comment]
Why won't you fix this? Whenever I do nested forms, the inner form tags get deleted from what I've seen.

I run into instances where I have an overarching form that submits the full form, but then also need validation on subforms when adding an item to a collection. Is this not a valid use case? If I have just the main form and hit submit on an item collection, it activates all the elements on a form and that looks bad.

**Comment by Jakobovski** [comment]
You should not be nesting forms, it is a bad practice and goes against HTML5 spec.
http://stackoverflow.com/questions/379610/can-you-nest-html-forms
