### ISSUE TITLE
Validation doesn't work with name="name"

### ISSUE THREAD

**Issue by luklapp** [turinggroup/angular-validator#57]
Validation works perfectly for me, except when i have an input field in my form which has the name "name".

**Comment by frantisekjandos** [comment]
I vote for this bugfix, I spent 2 hours of investigation before finding luklapp's issue. Thanks! :-)

**Comment by aquasmit** [comment]
I also vote for this bug fix.. I experienced this issue.

**Comment by Jakobovski** [comment]
It seems to work for me. Can you send me a plunker of the issue? Maybe you have two fields with the same name? That will cause an issue.

**Comment by 12finger** [comment]
ok, same issue here.
i checked for a duplicate fielde named "name", but no ...

see: https://gist.github.com/12finger/f743d86509dea2a647d8

**Comment by 12finger** [comment]
i am spending hour after hour trying to debug this script ...
at least i found the failing one: 

`scope[element.form.name]` is `"undefined"` as soon as the form contains an input with `name="name"`


![errorrrr](https://cloud.githubusercontent.com/assets/1730022/11106438/907250f2-88d6-11e5-9d6d-28941b2bab94.jpg)

**Comment by 12finger** [comment]
but sorry, my Angular knowledge is limited, so i have no clue on how to circumvent this, i mean: how to improve the code, so `name` becomes a valid name.
@Jakobovski  any idea?

**Comment by 12finger** [comment]
yeah! just issued a PR #68 
fixes the name="name" problem.

**Comment by Jakobovski** [comment]
fixed
