### ISSUE TITLE
Form names with dots aren't supported

### ISSUE THREAD

**Issue by zortnac** [turinggroup/angular-validator#59]
Hey all,

Discovered that the dot in my form name was throwing an exception. I tried checking to make sure that dots are allowed in the name attribute (per HTML spec) before I raised an issue over it, and I actually couldn't find a definitive yes or no.

However AngularJS's form directive _does_ support dots in the names.

I have a pull request open with a suggested fix; any thoughts? 

I'm noticing now that there might be more places in the code that could suffer from the same bug, but before I go making the pull request a larger diff I figured I'd wait on some feedback.

Thanks.

**Comment by Jakobovski** [comment]
Thanks for the PR! Its been merged.
