### ISSUE TITLE
When closing a modal which contains the form, it attempts to submit?

### ISSUE THREAD

**Issue by henry74** [turinggroup/angular-validator#61]
I'm trying to close/hide a modal when a user clicks 'Cancel' instead of choosing to submit the form.  When I hide the modal it automatically submits the form.  Is there a proper function to call to cancel submission and prevent calling the function tied to angular-validator-submit?

**Comment by henry74** [comment]
Actually any ng-click event within the form automatically attempts to validate the entire form.  How do I avoid auto validating the form upon any ng-click event?

**Comment by Jakobovski** [comment]
Please create a jsfiddle demonstrating the issue the issue.  My hunch is you are clicking on a button and they `type` of the button is not defined, try this: `<button type='button>Click Me</button`

**Comment by henry74** [comment]
@Jakobovski Yes, you were right.  Didn't know I had to define the type="button" as a requirement.  Good to know.  I've created many clickable elements without using the type="button".  This is the first time it made a difference.  Appreciate the response!

**Comment by Jakobovski** [comment]
It's only an issue when in a form
Zohar Jackson
Lead Frontend Developer
C:  773-669-5033
C:  224-612-133i
O:  312-488-4690

On Sep 6, 2015 9:43 PM, Henry Hwangbo <notifications@github.com> wrote:Closed #61.
