### ISSUE TITLE
making an element invalid in controller

### ISSUE THREAD

**Issue by chamarts** [turinggroup/angular-validator#63]
hi,

is there a way I show the error message by setting $invalid to false on form element in controller function ? pls. let me know if this is something I can achieve. 

I have a field which fires a ajax request on update and I want to invalidate/validate the input based on 
response. 

thx
sri

**Comment by Jakobovski** [comment]
Just make a custom validation function, that returns false. You can have it look at some property on the model, or on a different model to determine validity.
