### ISSUE TITLE
Please add option to use standard Bootstrap style for validation errors 

### ISSUE THREAD

**Issue by tseshevsky** [turinggroup/angular-validator#64]
As far as I understand usual way to show validation error in Bootstrap form is to use the following markup:
```
<span class="field-validation-error help-block with-errors">Error message</span>
```
Could you add an option to use intstead of:
```
function generateErrorMessage(messageText) {
      return "<label class='control-label has-error validationMessage'>" + scope.$eval(messageText) + "</label>";
}
```
this method to generate error message: 
```
function generateErrorMessage(messageText) {
      return "<span class='field-validation-error help-block with-errors'>" + scope.$eval(messageText) + "</span>";
}
```
or provide a way to use templates.
Many thanks.

**Comment by Jakobovski** [comment]
Well there are two standard ways of doing this either with `help-block` or with `control-label`.  Where did `field-validation-error` come from, is that an old version of bootstrap?

I think the best option is to build out the ability for custom templates
