### ISSUE TITLE
Watching form length to add watches for new form elements is not enough

### ISSUE THREAD

**Issue by tseshevsky** [turinggroup/angular-validator#65]
I can change form in a number of ways, not only add new form elements.
I believe that this way is better:
```
 // Watch form length to add watches for new form elements
scope.$watch(function() {
	var key = Object.keys(scopeForm).join();
    return key;
}, function(){
    // Destroy all the watches
    // This is cleaner than figuring out which items are already being watched and only un-watching those.
    angular.forEach(watches, function(watch){watch();});
    setupWatches(DOMForm);
});
```

**Comment by Jakobovski** [comment]
Ya that is better. I have added the change to Version 2.0 which will be released in the upcoming weeks.

**Comment by Jakobovski** [comment]
Feel free to create a PR if you want it to be added to the 1.x version. I will merge, just change it to:
` return Object.keys(scopeForm).join();`
