### ISSUE TITLE
how it use with radio and check buttons ?

### ISSUE THREAD

**Issue by opium-draga** [turinggroup/angular-validator#66]
please, provide opportunity for use validation to radio and check buttons

**Comment by huei90** [comment]
@Jakobovski In the [angular-validation](https://github.com/huei90/angular-validation/) experiences, supporting radio and checkbox are kind of trouble, but at last, we use the attribute `validation-group` based on the feature `message-id` we have.

For your reference, this really a think make the validation going complicated. 

:beers:
