### ISSUE TITLE
Provide an option for feedback icons.

### ISSUE THREAD

**Issue by MacGyver27** [turinggroup/angular-validator#70]
Hey,

Let me first thank for the very useful directive!

Anyway to make it look better would you please consider adding to your directive functionality for feedback icons at the end of input field?

So far I have it implemented according to this stackoverflow [post](http://stackoverflow.com/a/32968734/4224113):

Like below (checkmark for OK, X for error and '*' for required): 
![ex](http://oi64.tinypic.com/9asktu.jpg)

Appreciate it! Thanks.

**Comment by nestorvanz** [comment]
This implementation works with Semantic UI?

**Comment by MacGyver27** [comment]
Never used Semantic UI.. anyway found this doing the trick: http://ngmodules.org/modules/ng-form-group
Thanks!

**Comment by nestorvanz** [comment]
Please create a version that works with Semantic UI

**Comment by Jakobovski** [comment]
Glad to hear you figured it out. Cheers.
