### ISSUE TITLE
Fixed issue form name with dot name="forms.formName"

### ISSUE THREAD

**Issue by AndersonRocha** [turinggroup/angular-validator#76]
Change scope[element.form.name] to scopeForm

Fixed the following:
----------------
Method "updateValidationMessage":

// Only add validation messages if the form field is $dirty or the form has been submitted
if (scopeElementModel.$dirty || (scope[element.form.name] && scope[element.form.name].submitted)) {
(...)

to

// Only add validation messages if the form field is $dirty or the form has been submitted
if (scopeElementModel.$dirty || scopeForm.submitted) {
(...)

----------------------------------
Method "updateValidationClass":

// Only add/remove validation classes if the field is $dirty or the form has been submitted
if (formField.$dirty || (scope[element.form.name] && scope[element.form.name].submitted)) {
(...)

to

// Only add/remove validation classes if the field is $dirty or the form has been submitted
if (formField.$dirty || scopeForm.submitted) {
(...)

**Comment by Jakobovski** [comment]
Please create a pull request.

**Comment by AndersonRocha** [comment]
Created.
