### ISSUE TITLE
How to set that element is valid or not inside Javascript  ?

### ISSUE THREAD

**Issue by sincerekamal** [turinggroup/angular-validator#79]
Hi guys,
I want to how to set that element is valid or not from Javascript. For instance, after submitting the form there may be "username exist" error, is there any way to set the flag ? or else I need to do as manually what I do now ?

**Comment by Jakobovski** [comment]
See https://github.com/turinggroup/angular-validator/issues/75

You can use `$scope.myFormName.fieldName.$setValidity()`. Take a look at the source
