### ISSUE TITLE
Multiple Calls to Custom Validator Function when validate-on is blur

### ISSUE THREAD

**Issue by gregp55305** [turinggroup/angular-validator#82]
Maybe I am missing something, but the code in my custom validator function is getting called every time the user enters data in the field and not just once during the blur event. Even more interesting, it also gets called when the user enters data in another field. I assumed that I must be doing something wrong, but I slightly modified the Plunker example and it is working the same way there too. I need to perform some expensive validation for this particular field and want to do it as infrequently as possible.

**Comment by Jakobovski** [comment]
If you have expensive validation this library is not right for you.
