### ISSUE TITLE
Dows not been called inside a <ng-form> tag

### ISSUE THREAD

**Issue by gino8080** [turinggroup/angular-validator#84]
Hello,

how can i make it working inside a ng-form tag?

[this is the plunker with the problem](http://plnkr.co/edit/Qx9Hvqe5qhkEqRiK38Oi?p=preview)

thank you very much!

**Comment by Jakobovski** [comment]
You have a form inside of a form. This is not w3c compliant HTML. You should not do this.

**Comment by gino8080** [comment]
So ng-form is not an usable solution?

Please how to check for validation of some fields of a multi step form?

**Comment by Jakobovski** [comment]
you can use ng-form but you cant use it inside of another form. Thats not how ng-form is made to be used

**Comment by gino8080** [comment]
So I have to use ng-forms without a parent/father <form> tag?
Can can you edit my plunker to show me how to use angular-validator on them ?

thank you very much
